version: "3.9"
services:
  postgres:
    container_name: gc_postgres
    image: postgis/postgis:13-master
    restart: "no"
    volumes:
      - "../sql/:/docker-entrypoint-initdb.d/"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOSTNAME: localhost
    ports:
      - "3999:5432"